import express from "express";

import applications from "./applications.routes.js";
import auth from "./auth.routes.js";
import blogRouter from "./blog.route.js";
import buyer from "./buyer.js";
import admin from "./admin.routes.js";
import calendars from "./calendar.routes.js";
import categorys from "./category.routes.js";
import chatRouter from "./chat.routes.js";
import chats from "./chats.js";
import comments from "./comments.routes.js";
import contacts from "./contacts.js";
import disputeRoutes from "./disputes.js";
import educations from "./educations.js";
import identityVerifications from "./identityVerifications.js";
import jobs from "./job.routes.js";
import jobwishlists from "./jobWishlist.routes.js";
import messages from "./messages.js";
import notifications from "./notifications.js";
import orders from "./orders.js";
import packages from "./packages.js";
import paymentMethods from "./paymentMethods.js";
import portfolios from "./portfolio.routes.js";
import refers from "./referral.routes.js";
import reviews from "./reviews.routes.js";
import seller from "./seller.js";
import services from "./services.js";
import subscribes from "./subscribe.routes.js";
import talents from "./talent.routes.js";
import talentwishlists from "./talentWishlist.routes.js";
import royalty from "./royalty.routes.js";
import transactions from "./transactions.js";
import users from "./users.js";
import views from "./views.routes.js";
import stripeRoutes from "./stripe.routes.js";
import balanceRoutes from "./balance.routes.js";
import paypalRoutes from "./paypal.routes.js";

import withdraws from "./withdraws.js";

const router = express.Router();

router.use("/stripe", stripeRoutes);
router.use("/paypal", paypalRoutes);
router.use("/contacts", contacts);
router.use("/admin", admin);
router.use("/contacts", contacts);
router.use("/users", users);
router.use("/educations", educations);
router.use("/balances", balanceRoutes);
router.use("/portfolios", portfolios);
router.use("/auth", auth);
router.use("/categorys", categorys);
router.use("/services", services);
router.use("/packages", packages);
router.use("/jobs", jobs);
router.use("/comments", comments);
router.use("/applications", applications);
router.use("/chats", chats);
router.use("/chat", chatRouter);
router.use("/blog", blogRouter);
router.use("/messages", messages);
router.use("/buyer", buyer);
router.use("/seller", seller);
router.use("/royalty", royalty);
router.use("/talents", talents);
router.use("/orders", orders);
router.use("/disputes", disputeRoutes);
router.use("/notifications", notifications);
router.use("/payment-methods", paymentMethods);
router.use("/withdraws", withdraws);
router.use("/transactions", transactions);
router.use("/verifications", identityVerifications);
router.use("/refers", refers);
router.use("/subscribes", subscribes);
router.use("/calendars", calendars);
router.use("/views", views);
router.use("/talentwishlist", talentwishlists);
router.use("/jobwishlist", jobwishlists);
router.use("/reviews", reviews);

export default router;
